name: butcetakip
description: A new Flutter project.

version: 2.1.1+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  sqflite: ^2.2.6
  path: ^1.8.0
  flutter_riverpod: ^2.3.2
  d_chart: ^3.0.0
  csv: ^6.0.0
  permission_handler: ^12.0.1
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0
  path_provider: ^2.0.15
  google_mobile_ads: ^6.0.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.6.1
  google_sign_in: ^6.1.0
  firebase_auth: ^4.2.8
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  device_info_plus: ^11.5.0
  url_launcher: ^6.0.0
  toggle_switch: ^2.1.0
  dropdown_button2: any
  app_settings: ^6.1.1
  http: any
  ntp: ^2.0.0
  shared_preferences: ^2.2.0
  syncfusion_flutter_charts: ^30.2.4
  home_widget: ^0.8.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/image/
    - assets/icons/
    - assets/image/icon_BKA/

  fonts:
    - family: FontRegular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: FontBold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
    - family: FontMedium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf
    - family: FontSemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
    - family: FontLight
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf