import 'package:butcekontrol/Riverpod/update_data_riverpod.dart';
import 'package:butcekontrol/Riverpod/appbar_type_2_riverpod.dart';
import 'package:butcekontrol/Riverpod/settings_riverpod.dart';
import 'package:butcekontrol/riverpod/currency_riverpod.dart';
import 'package:butcekontrol/riverpod/ggl_drive_riverpod.dart';
import 'package:butcekontrol/riverpod/montly_info_riverpod.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'Riverpod/bottom_nav_bar_riverpod.dart';
import 'Riverpod/database_provider.dart';
import 'Riverpod/calendar_riverpod.dart';
import 'Riverpod/category_info_riverpod.dart';
import 'Riverpod/daily_info_riverpod.dart';
import 'Riverpod/home_riverpod.dart';
import 'Riverpod/statistics_riverpod.dart';
import 'Riverpod/asset_riverpod.dart';

final botomNavBarRiverpod = ChangeNotifierProvider((ref) => BottomNavBarRiverpod());
final databaseRiverpod = ChangeNotifierProvider((ref) => DbProvider());
final homeRiverpod = ChangeNotifierProvider((ref) => HomeRiverpod());
final appBarTypeProvider = ChangeNotifierProvider((ref) => AppBarType2Riverpod());
final calendarRiverpod = ChangeNotifierProvider((ref) => CalendarRiverpod());
final dailyInfoRiverpod = ChangeNotifierProvider((ref) => DailyInfoRiverpod());
final statisticsRiverpod = ChangeNotifierProvider((ref) => StatisticsRiverpod());
final categoryInfoRiverpod = ChangeNotifierProvider((ref) => CategoryInfoRiverpod());
final settingsRiverpod = ChangeNotifierProvider((ref) => SettingsRiverpod());
final updateDataRiverpod = ChangeNotifierProvider((ref) => UpdateDataRiverpod());
final gglDriveRiverpod = ChangeNotifierProvider((ref) => GglDriveRiverpod());
final currencyRiverpod = ChangeNotifierProvider((ref) => CurrencyRiverpod());
final montlyInfoRiverpod = ChangeNotifierProvider((ref) => MontlyInfoRiverpod());
final assetRiverpod = ChangeNotifierProvider((ref) => AssetRiverpod());